version: '3'
services:
  backend:
    env_file: .env
    build:
      context: .
    restart: always
    command: /bin/bash -c "python3 wait_for_db.py && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    env_file: .env
    ports:
      - "5432:5432"